# Generated by Django 5.0.7 on 2024-08-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comments_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default=None, max_length=100)),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auctions.auctions')),
            ],
        ),
    ]
