# Generated by Django 5.0.7 on 2024-08-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctions',
            old_name='start_bid',
            new_name='starting_bid',
        ),
        migrations.AlterField(
            model_name='auctions',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
