# Generated by Django 5.0.7 on 2024-08-23 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_start_bid_auctions_starting_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
